[ERROR] 2021-09-11 13:42:21,131 | /home/server-admin/Projects/Gopi/Training/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-09-11 13:42:20.643185-127.0.0.1-412
